name: planting-grass

on:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          git config user.name guriOH
          git config user.email stockhoon5@gmail.com
          git add .
          git commit -m "generated"
          git push
